/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ff3.4--git--ijk0.8.7--20200911--001"
#endif /* AVUTIL_FFVERSION_H */
