/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "ff4.0--ijk0.8.8--20210205--001"
#endif /* AVUTIL_FFVERSION_H */
